import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:easylocation_mvp/models/property/property.dart';

extension PropertySerializer on Property {
  Map<String, dynamic> toJson() {
    return {
      'bailleurId': bailleurId,
      'moderationStatus': moderationStatus,
      'typeBien': typeBien,
      'categorie': categorie,
      'province': province,
      'provinceKey': provinceKey,
      'provinceLabel': provinceLabel,
      'provinceSpecifique': provinceSpecifique,
      'ville': ville,
      'villeKey': villeKey,
      'villeLabel': villeLabel,
      'villeSpecifique': villeSpecifique,
      'commune': commune,
      'communeKey': communeKey,
      'communeLabel': communeLabel,
      'communeSpecifique': communeSpecifique,
      'quartier': quartier,
      'quartierKey': quartierKey,
      'quartierLabel': quartierLabel,
      'quartierSpecifique': quartierSpecifique,
      'avenue': avenue,
      'avenueKey': avenueKey,
      'avenueLabel': avenueLabel,
      'avenueSpecifique': avenueSpecifique,
      'numeroMaison': numeroMaison,
      'price': price,
      'nombreChambres': nombreChambres,
      'garantieIdeale': garantieIdeale,
      'garantieMinimale': garantieMinimale,
      'disponibiliteImmediate': disponibiliteImmediate,
      'dateDisponibilite': dateDisponibilite != null ? Timestamp.fromDate(dateDisponibilite!) : null,
      'maisonEnEtage': maisonEnEtage,
      'niveauEtage': niveauEtage,
      'description': description,
      'hasSalon': hasSalon,
      'hasCuisine': hasCuisine,
      'hasToiletteParentale': hasToiletteParentale,
      'selectedTypeSol': selectedTypeSol,
      'hasGarage': hasGarage,
      'hasCourRecreation': hasCourRecreation,
      'hasDepot': hasDepot,
      'maisonEnclos': maisonEnclos,
      'possibiliteAnimaux': possibiliteAnimaux,
      'typeMaison': typeMaison,
      'hasEau': hasEau,
      'compteurEau': compteurEau,
      'electricite': electricite,
      'accessibiliteVoiture': accessibiliteVoiture,
      'bailleurHabiteAvec': bailleurHabiteAvec,
      'nombreMenages': nombreMenages,
      'nomProprietaire': nomProprietaire,
      'postnomProprietaire': postnomProprietaire,
      'prenomProprietaire': prenomProprietaire,
      'telephoneProprietaire': telephoneProprietaire,
      'emailProprietaire': emailProprietaire,
      'statutLegal': statutLegal,
      'statutLegalAutre': statutLegalAutre,
      'statutProfessionnel': statutProfessionnel,
      'statutProAutre': statutProAutre,
      'estReactif': estReactif,
      'nomBailleur': nomBailleur,
      'telBailleur': telBailleur,
      'categorieEligible': categorieEligible,
      'serviceEligible': serviceEligible,
      'publicationDate': publicationDate != null ? Timestamp.fromDate(publicationDate!) : null,
      'createdAt': Timestamp.fromDate(createdAt),
      'lastBoost': lastBoost != null ? Timestamp.fromDate(lastBoost!) : null,
      'sortIndex': sortIndex,
      'views': views,
      'derniere_vue': derniereVue != null ? Timestamp.fromDate(derniereVue!) : null,
      'shares': shares,
      'favoriteCount': favoriteCount,
      'averageRating': averageRating,
      'ratingCount': ratingCount,
      'totalRating': totalRating,
      'status': status,
      'statusPriority': statusPriority,
      'isHiddenFromBailleur': isHiddenFromBailleur,
      'isVerified': isVerified,
      'hasPriorityRequest': hasPriorityRequest,
      'priorityStatus': priorityStatus,
      'priorityRequestAt': priorityRequestAt != null ? Timestamp.fromDate(priorityRequestAt!) : null,
      'processingStatus': processingStatus,
      'assignedAdminId': assignedAdminId,
      'assignedAdminName': assignedAdminName,
      'lastUpdateBy': lastUpdateBy,
      'lockTimestamp': lockTimestamp,
      'lockedBy': lockedBy,
      'lastLocataireId': lastLocataireId,
      'specificImageUrls': specificImageUrls,
      'chambresImageUrls': chambresImageUrls,
      'imageUrls': firestoreImageUrls,
      'mainImageUrl': mainImageUrl,
    };
  }
}