// lib/models/property/property_copy_with.dart

import 'package:easylocation_mvp/models/property/property.dart';

extension PropertyCopyWith on Property {
  Property copyWith({
    String? id,
    String? bailleurId,
    String? moderationStatus,
    String? typeBien,
    String? categorie,
    String? province,
    String? provinceKey,
    String? provinceLabel,
    String? provinceSpecifique,
    String? ville,
    String? villeKey,
    String? villeLabel,
    String? villeSpecifique,
    String? commune,
    String? communeKey,
    String? communeLabel,
    String? communeSpecifique,
    String? quartier,
    String? quartierKey,
    String? quartierLabel,
    String? quartierSpecifique,
    String? avenue,
    String? avenueKey,
    String? avenueLabel,
    String? avenueSpecifique,
    String? numeroMaison,
    double? price,
    int? nombreChambres,
    int? garantieIdeale,
    int? garantieMinimale,
    bool? disponibiliteImmediate,
    DateTime? dateDisponibilite,
    bool? maisonEnEtage,
    int? niveauEtage,
    String? description,
    bool? hasSalon,
    bool? hasCuisine,
    bool? hasToiletteParentale,
    String? selectedTypeSol,
    bool? hasGarage,
    bool? hasCourRecreation,
    bool? hasDepot,
    bool? maisonEnclos,
    bool? possibiliteAnimaux,
    String? typeMaison,
    bool? hasEau,
    bool? compteurEau,
    String? electricite,
    bool? accessibiliteVoiture,
    bool? bailleurHabiteAvec,
    int? nombreMenages,
    String? nomProprietaire,
    String? postnomProprietaire,
    String? prenomProprietaire,
    String? telephoneProprietaire,
    String? emailProprietaire,
    String? statutLegal,
    String? statutLegalAutre,
    String? statutProfessionnel,
    String? statutProAutre,
    bool? estReactif,
    String? nomBailleur,
    String? telBailleur,
    String? categorieEligible,
    String? serviceEligible,
    DateTime? publicationDate,
    DateTime? createdAt,
    DateTime? lastBoost,
    int? sortIndex,
    int? views,
    DateTime? derniereVue,
    int? shares,
    int? favoriteCount,
    double? averageRating,
    int? ratingCount,
    double? totalRating,
    String? status,
    int? statusPriority,
    bool? isHiddenFromBailleur,
    bool? isVerified,
    bool? hasPriorityRequest,
    String? priorityStatus,
    DateTime? priorityRequestAt,
    String? processingStatus,
    String? assignedAdminId,
    String? assignedAdminName,
    String? lastUpdateBy,
    int? lockTimestamp,
    String? lockedBy,
    String? lastLocataireId,
    Map<String, String>? specificImageUrls,
    List<String>? chambresImageUrls,
    List<String>? firestoreImageUrls,
    String? mainImageUrl,
  }) {
    return Property(
      id: id ?? this.id,
      bailleurId: bailleurId ?? this.bailleurId,
      moderationStatus: moderationStatus ?? this.moderationStatus,
      typeBien: typeBien ?? this.typeBien,
      categorie: categorie ?? this.categorie,
      province: province ?? this.province,
      provinceKey: provinceKey ?? this.provinceKey,
      provinceLabel: provinceLabel ?? this.provinceLabel,
      provinceSpecifique: provinceSpecifique ?? this.provinceSpecifique,
      ville: ville ?? this.ville,
      villeKey: villeKey ?? this.villeKey,
      villeLabel: villeLabel ?? this.villeLabel,
      villeSpecifique: villeSpecifique ?? this.villeSpecifique,
      commune: commune ?? this.commune,
      communeKey: communeKey ?? this.communeKey,
      communeLabel: communeLabel ?? this.communeLabel,
      communeSpecifique: communeSpecifique ?? this.communeSpecifique,
      quartier: quartier ?? this.quartier,
      quartierKey: quartierKey ?? this.quartierKey,
      quartierLabel: quartierLabel ?? this.quartierLabel,
      quartierSpecifique: quartierSpecifique ?? this.quartierSpecifique,
      avenue: avenue ?? this.avenue,
      avenueKey: avenueKey ?? this.avenueKey,
      avenueLabel: avenueLabel ?? this.avenueLabel,
      avenueSpecifique: avenueSpecifique ?? this.avenueSpecifique,
      numeroMaison: numeroMaison ?? this.numeroMaison,
      price: price ?? this.price,
      nombreChambres: nombreChambres ?? this.nombreChambres,
      garantieIdeale: garantieIdeale ?? this.garantieIdeale,
      garantieMinimale: garantieMinimale ?? this.garantieMinimale,
      disponibiliteImmediate: disponibiliteImmediate ?? this.disponibiliteImmediate,
      dateDisponibilite: dateDisponibilite ?? this.dateDisponibilite,
      maisonEnEtage: maisonEnEtage ?? this.maisonEnEtage,
      niveauEtage: niveauEtage ?? this.niveauEtage,
      description: description ?? this.description,
      hasSalon: hasSalon ?? this.hasSalon,
      hasCuisine: hasCuisine ?? this.hasCuisine,
      hasToiletteParentale: hasToiletteParentale ?? this.hasToiletteParentale,
      selectedTypeSol: selectedTypeSol ?? this.selectedTypeSol,
      hasGarage: hasGarage ?? this.hasGarage,
      hasCourRecreation: hasCourRecreation ?? this.hasCourRecreation,
      hasDepot: hasDepot ?? this.hasDepot,
      maisonEnclos: maisonEnclos ?? this.maisonEnclos,
      possibiliteAnimaux: possibiliteAnimaux ?? this.possibiliteAnimaux,
      typeMaison: typeMaison ?? this.typeMaison,
      hasEau: hasEau ?? this.hasEau,
      compteurEau: compteurEau ?? this.compteurEau,
      electricite: electricite ?? this.electricite,
      accessibiliteVoiture: accessibiliteVoiture ?? this.accessibiliteVoiture,
      bailleurHabiteAvec: bailleurHabiteAvec ?? this.bailleurHabiteAvec,
      nombreMenages: nombreMenages ?? this.nombreMenages,
      nomProprietaire: nomProprietaire ?? this.nomProprietaire,
      postnomProprietaire: postnomProprietaire ?? this.postnomProprietaire,
      prenomProprietaire: prenomProprietaire ?? this.prenomProprietaire,
      telephoneProprietaire: telephoneProprietaire ?? this.telephoneProprietaire,
      emailProprietaire: emailProprietaire ?? this.emailProprietaire,
      statutLegal: statutLegal ?? this.statutLegal,
      statutLegalAutre: statutLegalAutre ?? this.statutLegalAutre,
      statutProfessionnel: statutProfessionnel ?? this.statutProfessionnel,
      statutProAutre: statutProAutre ?? this.statutProAutre,
      estReactif: estReactif ?? this.estReactif,
      nomBailleur: nomBailleur ?? this.nomBailleur,
      telBailleur: telBailleur ?? this.telBailleur,
      categorieEligible: categorieEligible ?? this.categorieEligible,
      serviceEligible: serviceEligible ?? this.serviceEligible,
      publicationDate: publicationDate ?? this.publicationDate,
      createdAt: createdAt ?? this.createdAt,
      lastBoost: lastBoost ?? this.lastBoost,
      sortIndex: sortIndex ?? this.sortIndex,
      views: views ?? this.views,
      derniereVue: derniereVue ?? this.derniereVue,
      shares: shares ?? this.shares,
      favoriteCount: favoriteCount ?? this.favoriteCount,
      averageRating: averageRating ?? this.averageRating,
      ratingCount: ratingCount ?? this.ratingCount,
      totalRating: totalRating ?? this.totalRating,
      status: status ?? this.status,
      statusPriority: statusPriority ?? this.statusPriority,
      isHiddenFromBailleur: isHiddenFromBailleur ?? this.isHiddenFromBailleur,
      isVerified: isVerified ?? this.isVerified,
      hasPriorityRequest: hasPriorityRequest ?? this.hasPriorityRequest,
      priorityStatus: priorityStatus ?? this.priorityStatus,
      priorityRequestAt: priorityRequestAt ?? this.priorityRequestAt,
      processingStatus: processingStatus ?? this.processingStatus,
      assignedAdminId: assignedAdminId ?? this.assignedAdminId,
      assignedAdminName: assignedAdminName ?? this.assignedAdminName,
      lastUpdateBy: lastUpdateBy ?? this.lastUpdateBy,
      lockTimestamp: lockTimestamp ?? this.lockTimestamp,
      lockedBy: lockedBy ?? this.lockedBy,
      lastLocataireId: lastLocataireId ?? this.lastLocataireId,
      specificImageUrls: specificImageUrls ?? this.specificImageUrls,
      chambresImageUrls: chambresImageUrls ?? this.chambresImageUrls,
      firestoreImageUrls: firestoreImageUrls ?? this.firestoreImageUrls,
      mainImageUrl: mainImageUrl ?? this.mainImageUrl,
    );
  }
}