// lib/models/formulaire_publication/formulaire_publication_copy_with.dart
import 'formulaire_publication.dart';
import 'formulaire_publication_image_source.dart';

extension FormulairePublicationCopyWith on FormulairePublicationModel {
  FormulairePublicationModel copyWith({
    String? id,
    ImageSource? mainImage,
    String? typeBien,
    String? province,
    String? provinceSpecifique,
    String? ville,
    String? villeSpecifique,
    String? commune,
    String? communeSpecifique,
    String? quartier,
    String? quartierSpecifique,
    String? avenue,
    String? avenueSpecifique,
    String? numeroMaison,
    double? price,
    int? garantieIdeale,
    int? garantieMinimale,
    bool? disponibiliteImmediate,
    DateTime? dateDisponibilite,
    bool? maisonEnEtage,
    int? niveauEtage,
    String? description,
    String? moderationStatus,
    int? nombreChambres,
    bool? hasSalon,
    bool? hasCuisine,
    bool? hasToiletteParentale,
    String? selectedTypeSol,
    bool? hasGarage,
    bool? hasCourRecreation,
    bool? hasDepot,
    Object? cuisineImage = FormulairePublicationModelSentinel,
    Object? toiletteParentaleImage = FormulairePublicationModelSentinel,
    Object? salonImage = FormulairePublicationModelSentinel,
    Object? garageImage = FormulairePublicationModelSentinel,
    Object? courRecreationImage = FormulairePublicationModelSentinel,
    Object? depotImage = FormulairePublicationModelSentinel,
    List<ImageSource>? chambresImages,
    bool? maisonEnclos,
    bool? possibiliteAnimaux,
    String? typeMaison,
    bool? hasEau,
    bool? compteurEau,
    String? electricite,
    bool? accessibiliteVoiture,
    bool? bailleurHabiteAvec,
    int? nombreMenages,
    bool? estReactif,
    String? bailleurId,
    String? nomProprietaire,
    String? postnomProprietaire,
    String? prenomProprietaire,
    String? telephoneProprietaire,
    String? emailProprietaire,
    String? statutLegal,
    String? statutLegalAutre,
    String? statutProfessionnel,
    String? statutProAutre,
    String? nomBailleur,
    String? telBailleur,
    String? categorieEligible,
    String? serviceEligible,
  }) {
    return FormulairePublicationModel(
      id: id ?? this.id,
      mainImage: mainImage ?? this.mainImage,
      typeBien: typeBien ?? this.typeBien,
      province: province ?? this.province,
      provinceSpecifique: provinceSpecifique ?? this.provinceSpecifique,
      ville: ville ?? this.ville,
      villeSpecifique: villeSpecifique ?? this.villeSpecifique,
      commune: commune ?? this.commune,
      communeSpecifique: communeSpecifique ?? this.communeSpecifique,
      quartier: quartier ?? this.quartier,
      quartierSpecifique: quartierSpecifique ?? this.quartierSpecifique,
      avenue: avenue ?? this.avenue,
      avenueSpecifique: avenueSpecifique ?? this.avenueSpecifique,
      numeroMaison: numeroMaison ?? this.numeroMaison,
      price: price ?? this.price,
      garantieIdeale: garantieIdeale ?? this.garantieIdeale,
      garantieMinimale: garantieMinimale ?? this.garantieMinimale,
      disponibiliteImmediate: disponibiliteImmediate ?? this.disponibiliteImmediate,
      dateDisponibilite: dateDisponibilite ?? this.dateDisponibilite,
      maisonEnEtage: maisonEnEtage ?? this.maisonEnEtage,
      niveauEtage: niveauEtage ?? this.niveauEtage,
      description: description ?? this.description,
      moderationStatus: moderationStatus ?? this.moderationStatus,
      nombreChambres: nombreChambres ?? this.nombreChambres,
      hasSalon: hasSalon ?? this.hasSalon,
      hasCuisine: hasCuisine ?? this.hasCuisine,
      hasToiletteParentale: hasToiletteParentale ?? this.hasToiletteParentale,
      selectedTypeSol: selectedTypeSol ?? this.selectedTypeSol,
      hasGarage: hasGarage ?? this.hasGarage,
      hasCourRecreation: hasCourRecreation ?? this.hasCourRecreation,
      hasDepot: hasDepot ?? this.hasDepot,
      cuisineImage: cuisineImage == FormulairePublicationModelSentinel ? this.cuisineImage : (cuisineImage as ImageSource?),
      toiletteParentaleImage: toiletteParentaleImage == FormulairePublicationModelSentinel ? this.toiletteParentaleImage : (toiletteParentaleImage as ImageSource?),
      salonImage: salonImage == FormulairePublicationModelSentinel ? this.salonImage : (salonImage as ImageSource?),
      garageImage: garageImage == FormulairePublicationModelSentinel ? this.garageImage : (garageImage as ImageSource?),
      courRecreationImage: courRecreationImage == FormulairePublicationModelSentinel ? this.courRecreationImage : (courRecreationImage as ImageSource?),
      depotImage: depotImage == FormulairePublicationModelSentinel ? this.depotImage : (depotImage as ImageSource?),
      chambresImages: chambresImages ?? this.chambresImages,
      maisonEnclos: maisonEnclos ?? this.maisonEnclos,
      possibiliteAnimaux: possibiliteAnimaux ?? this.possibiliteAnimaux,
      typeMaison: typeMaison ?? this.typeMaison,
      hasEau: hasEau ?? this.hasEau,
      compteurEau: compteurEau ?? this.compteurEau,
      electricite: electricite ?? this.electricite,
      accessibiliteVoiture: accessibiliteVoiture ?? this.accessibiliteVoiture,
      bailleurHabiteAvec: bailleurHabiteAvec ?? this.bailleurHabiteAvec,
      nombreMenages: nombreMenages ?? this.nombreMenages,
      estReactif: estReactif ?? this.estReactif,
      bailleurId: bailleurId ?? this.bailleurId,
      nomProprietaire: nomProprietaire ?? this.nomProprietaire,
      postnomProprietaire: postnomProprietaire ?? this.postnomProprietaire,
      prenomProprietaire: prenomProprietaire ?? this.prenomProprietaire,
      telephoneProprietaire: telephoneProprietaire ?? this.telephoneProprietaire,
      emailProprietaire: emailProprietaire ?? this.emailProprietaire,
      statutLegal: statutLegal ?? this.statutLegal,
      statutLegalAutre: statutLegalAutre ?? this.statutLegalAutre,
      statutProfessionnel: statutProfessionnel ?? this.statutProfessionnel,
      statutProAutre: statutProAutre ?? this.statutProAutre,
      nomBailleur: nomBailleur ?? this.nomBailleur,
      telBailleur: telBailleur ?? this.telBailleur,
      categorieEligible: categorieEligible ?? this.categorieEligible,
      serviceEligible: serviceEligible ?? this.serviceEligible,
    );
  }
}