// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYteHbtOTZQHjh19-WSPQDNtOPxhJWMpA',
    appId: '1:203205473215:web:b1765d04992f4fa304270a',
    messagingSenderId: '203205473215',
    projectId: 'easylocation-dev',
    authDomain: 'easylocation-dev.firebaseapp.com',
    storageBucket: 'easylocation-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIiQ4Oy4Jj-ySEmYauBFQ8KGZr3oUunus',
    appId: '1:203205473215:android:ad42d6f60507110b04270a',
    messagingSenderId: '203205473215',
    projectId: 'easylocation-dev',
    storageBucket: 'easylocation-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5nQdBu02frWkm3aO-N4ZVKsjsteaQX_4',
    appId: '1:203205473215:ios:6b02784c7466314804270a',
    messagingSenderId: '203205473215',
    projectId: 'easylocation-dev',
    storageBucket: 'easylocation-dev.firebasestorage.app',
    iosBundleId: 'com.example.easylocationMvp',
  );
}
