// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhm2zRZ3ZwpVepnQO8p_uu8ho4gU5g9d4',
    appId: '1:540611988411:web:922ba2df8746edce5a529e',
    messagingSenderId: '540611988411',
    projectId: 'easylocation-be28b',
    authDomain: 'easylocation-be28b.firebaseapp.com',
    storageBucket: 'easylocation-be28b.firebasestorage.app',
    measurementId: 'G-QDE23FP54E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3k9CvIS9hz_o9jayRVaofeENN1YnF6Qc',
    appId: '1:540611988411:android:28daa77497e234585a529e',
    messagingSenderId: '540611988411',
    projectId: 'easylocation-be28b',
    storageBucket: 'easylocation-be28b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBKYlAVvErjNXB1Sxx7GG0liFfbfFpxoc',
    appId: '1:540611988411:ios:9afc83953b1cdc205a529e',
    messagingSenderId: '540611988411',
    projectId: 'easylocation-be28b',
    storageBucket: 'easylocation-be28b.firebasestorage.app',
    iosBundleId: 'com.example.easylocationMvp',
  );
}
